services:
  momments-backend:
    build: .
    container_name: momments-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - momments-db

  momments-db:
    image: postgres:16
    container_name: momments-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8" # Set UTF-8 Encoding for storing Unicode characters
    ports:
      - "5432:5432"
    volumes:
      - momments_pg_data:/var/lib/postgresql/data

volumes:
  momments_pg_data: